name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5' # Replace with your desired Flutter version

    - name: Get dependencies
      run: |
        flutter pub get
        flutter clean
        sed -i "s/^org.gradle.java.home.*//" android/gradle.properties
        flutter doctor --android-licenses

    - name: Build APK
      run: flutter build apk --release --no-sound-null-safety
    
    - name: Build Release APK
      run: zip -r app_release.zip build/app/outputs/flutter-apk/
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: ${{ github.workspace }}/app_release.zip

  send_to_telegram:
    name: Send APK to Telegram Group
    runs-on: ubuntu-latest
    needs: release

    steps:
    - name: Download APK Artifact
      uses: actions/download-artifact@v2
      with:
        name: release-apk

    - name: Send to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_GROUP_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
            Commit Message: ${{ github.event.head_commit.message }}
            Commited Actor: ${{ github.actor }}
            Build Info: https://github.com/${{github.repository}}/commit/${{github.sha}}/checks
            Build Status: ${{ job.status }}
        document: ${{ github.workspace }}/app_release.zip
